---

- include: map.yml

- name: /etc/pam.d/<service>
  template:
    src: pam.j2
    dest: "/etc/pam.d/{{ service.key }}"
    owner: root
    group: root
    mode: '0644'
  vars:
    service: service.value
  loop: '{{ pam | dict2items }}'
  loop_control:
    loop_var: service
