---

- name: load variables
  include_vars:
    file: "{{ map }}.yml"
    name: "{{ map }}"
  loop:
    - default
    - osfamilymap
    - distributionmap
    - fingerprintmap
  loop_control:
    loop_var: map

- name: compute fingerprint
  set_fact:
    ansible_fingerprint: "{{ ansible_distribution+(ansible_distribution_major_version != 'NA') | ternary(ansible_distribution_major_version, '') }}"

- name: compute configuration
  set_fact:
    map: "{{ default.map | default({}) | combine(
      osfamilymap[ansible_os_family].map is defined | ternary(osfamilymap[ansible_os_family].map, {}),
      distributionmap[ansible_distribution].map is defined | ternary(distributionmap[ansible_distribution].map, {}),
      fingerprintmap[ansible_fingerprint].map is defined | ternary(fingerprintmap[ansible_fingerprint].map, {}),
      map | default({}),
      recursive=True
      ) }}"
